services:
  post_gui:
    user: "${UID:-1000}:${GID:-1000}"
    build:
      context: .
      dockerfile: Dockerfile.post_updater
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ${XAUTHORITY:-~/.Xauthority}:/root/.Xauthority
      - ..:/app
      - ${OBSIDIAN_PATH}:/app/obsidian:ro
      - ${OBSIDIAN_PATH}:/input/obsidian:ro
    environment:
      - DISPLAY=${DISPLAY}
      - XAUTHORITY=/root/.Xauthority
      - QT_X11_NO_MITSHM=1
    network_mode: "host"
    privileged: true
    ipc: host  # Add this for X11 shared memory
    command: python3 /app/scripts/post_gui.py

  view_page:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ../:/usr/share/nginx/html:ro