# Use an official Python runtime as a parent image
FROM python:3.9-slim

# Set the working directory in the container
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY scripts /app

# Install BeautifulSoup4
RUN pip install --no-cache-dir beautifulsoup4

# Run update_posts.py when the container launches
CMD ["python", "update_posts.py"]